import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import JourneyNavbar from "./components/JourneyNavbar";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-white text-gray-900">
        <JourneyNavbar />
        {children}
      </body>
    </html>
  );
}
